version: "3.3"
services:
  ###############
  #Load Balancer#
  postgres-kong-database:
    image: postgres:11
    ports:
      - "9955:5432"
    environment:
      - POSTGRES_PASSWORD=kong
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  load-balancer:
    image: andrebaceti/autoboostrap-kong:1.0
    depends_on:
      - postgres-kong-database
    ports:
      - "8080:8000"
      - "8001:8001"
      - "8443:8443"
      - "7946:7946"
      - "7946:7946/udp"
  ###############

  ##########
  #RabbitMQ#
  rabbitmq-main:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=pumpwood
      - RABBITMQ_DEFAULT_PASS=pumpwood
  #########

  ###################
  #Auth Microservice#
  test-db-micropython-backend:
    image: andrebaceti/test-db-micropython-backend:$TEST_DB_MICROPYTHON_APP
    restart: always
    environment:
      - KONG_API=http://load-balancer:8001/
      - SERVICE_URL=http://test-db-micropython-backend:5000/
    ports:
      - 7000:5432

  # micropython-backend-app:
  #   image: andrebaceti/micropython-backend-app:$MICROPYTHON_APP
  #   restart: always
  #   environment:
  #     - SIGNUP=TRUE
  #     - TEST_MEDIA=/test_media
  #     - TEST_MEDIA_BK=/test_media_bk
  #
  # micropython-admin-static:
  #   image: andrebaceti/micropython-backend-static:$MICROPYTHON_STATIC
  ##################
